"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
export type EditorLanguage = "en" | "sv";
const copy = {
 en:{width:"Width",height:"Height",laminate:"Laminate",material:"Material",quantity:"Quantity",edge:"Cutline spacing",total:"Total",order:"Order stickers",review:"Review & checkout",print:"Production file after payment",images:"Images",text:"Text",graphics:"Graphics",color:"Color",shapes:"Shapes",undo:"Undo",redo:"Redo",exit:"Exit",exitConfirm:"Are you sure you want to exit?",uploadImage:"Upload image",uploadPrompt:"Add or drag files",dropPrompt:"Drop files here…",acceptedTypes:"Accepted file types",maxFileSize:"Maximum file size",removeImages:"Remove all images",addText:"Add text",sampleText:"Sample Text",textInput:"Text",fontSize:"Font size",textColor:"Text color",removeTexts:"Remove all text",backgroundColor:"Sticker background",backgroundHelp:"Choose Solid color under Material to print this color inside the die-cut contour.",colorCodeBackground:"Background color code",colorCodeText:"Text color code",selectMaterial:"Select material",moreInfo:"More info",solidColor:"Solid color",pieces:"pcs",perPiece:"/ pc",duplicate:"Duplicate",layers:"Layers",workspace:"Workspace",close:"Close",productionCheckout:"PRODUCTION CHECKOUT",artworkObjects:"Artwork objects",contourReady:"Die-cut contour ready",validatedPrice:"Server-validated price",calculating:"Calculating production price…",protectedWorkflow:"Protected production workflow",protectedCopy:"Previewing is free. Editable SVG and print-ready assets are generated server-side and released after payment—not downloaded from the browser.",createDraft:"Create secure order draft",draftCreated:"Order draft created",reference:"Reference",privateFile:"Your print file stays private and is released only after verified payment. Connect a payment provider before public launch.",flipVertical:"Flip vertically",flipHorizontal:"Flip horizontally",sendFront:"Send to front",sendBack:"Send to back",sendForward:"Send forward",sendBackward:"Send backward",centerElement:"Center element",deleteElement:"Delete element"},
 sv:{width:"Bredd",height:"Höjd",laminate:"Laminat",material:"Material",quantity:"Antal",edge:"Kantlinjeavstånd",total:"Totalt",order:"Beställ stickers",review:"Granska & betala",print:"Produktionsfil efter betalning",images:"Bilder",text:"Text",graphics:"Grafik",color:"Färg",shapes:"Former",undo:"Ångra",redo:"Gör om",exit:"Avsluta",exitConfirm:"Är du säker på att du vill avsluta?",uploadImage:"Ladda upp bild",uploadPrompt:"Lägg till eller dra filer",dropPrompt:"Släpp filerna här…",acceptedTypes:"Godkända filtyper",maxFileSize:"Maximal filstorlek",removeImages:"Ta bort alla bilder",addText:"Lägg till text",sampleText:"Exempeltext",textInput:"Text",fontSize:"Textstorlek",textColor:"Textfärg",removeTexts:"Ta bort all text",backgroundColor:"Stickerbakgrund",backgroundHelp:"Välj Enfärgad under Material för att trycka denna färg innanför stanskonturen.",colorCodeBackground:"Färgkod för bakgrund",colorCodeText:"Färgkod för text",selectMaterial:"Välj material",moreInfo:"Mer info",solidColor:"Enfärgad",pieces:"st",perPiece:"/ st",duplicate:"Duplicera",layers:"Lager",workspace:"Arbetsyta",close:"Stäng",productionCheckout:"PRODUKTIONSKASSA",artworkObjects:"Designelement",contourReady:"Stanskontur klar",validatedPrice:"Servervaliderat pris",calculating:"Beräknar produktionspris…",protectedWorkflow:"Skyddat produktionsflöde",protectedCopy:"Förhandsvisning är gratis. Redigerbar SVG och tryckfärdiga filer skapas på servern och lämnas ut efter betalning.",createDraft:"Skapa säkert orderutkast",draftCreated:"Orderutkast skapat",reference:"Referens",privateFile:"Din tryckfil är privat och lämnas endast ut efter verifierad betalning. Anslut en betalningsleverantör före publik lansering.",flipVertical:"Vänd vertikalt",flipHorizontal:"Vänd horisontellt",sendFront:"Lägg längst fram",sendBack:"Lägg längst bak",sendForward:"Flytta framåt",sendBackward:"Flytta bakåt",centerElement:"Centrera element",deleteElement:"Ta bort element"}
} as const;
export type EditorCopyKey=keyof typeof copy.en;
type Value={language:EditorLanguage;setLanguage:(value:EditorLanguage)=>void;t:(key:EditorCopyKey)=>string;formatCurrency:(value:number,decimals?:boolean)=>string;formatNumber:(value:number)=>string};
const Context=createContext<Value>({language:"en",setLanguage:()=>{},t:key=>copy.en[key],formatCurrency:value=>String(value),formatNumber:value=>String(value)});
export function EditorI18nProvider({children}:{children:React.ReactNode}){
 const [language,setLanguage]=useState<EditorLanguage>("en");
 useEffect(()=>{if(localStorage.getItem("sticker-online-language")==="sv")setLanguage("sv")},[]);
 useEffect(()=>{localStorage.setItem("sticker-online-language",language);document.documentElement.lang=language;document.title=language==="sv"?"Sticker Online – Designa stansade stickers":"Sticker Online – Design die-cut stickers"},[language]);
 const value=useMemo<Value>(()=>({language,setLanguage,t:key=>copy[language][key],formatCurrency:(value,decimals=true)=>new Intl.NumberFormat(language==="sv"?"sv-SE":"en-SE",{style:"currency",currency:"SEK",currencyDisplay:language==="sv"?"symbol":"code",minimumFractionDigits:decimals?2:0,maximumFractionDigits:decimals?2:0}).format(value),formatNumber:value=>new Intl.NumberFormat(language==="sv"?"sv-SE":"en-SE").format(value)}),[language]);
 return <Context.Provider value={value}>{children}</Context.Provider>;
}
export const useEditorI18n=()=>useContext(Context);
